import React from 'react'

const page = () => {
  return (
    <div className='bg-white w-full h-auto flex justify-center items-center flex-col'>
        <div className='p-6 w-full md:max-w-[780px] m-auto pt-10'>
          <h1 className="text-2xl md:text-4xl font-black text-center mb-10">California's 'Shine the Light'</h1>
          <p>Under California’s “Shine the Light” law, CA Civil Code § 1798.83, California residents who provide personal information in obtaining products or services for personal, family or household use are entitled to request and obtain from us once a calendar year information about the customer information we shared, if any, with any third parties. If applicable, this information would include the categories of customer information and the names and addresses of those businesses with which we shared customer information for the immediately prior calendar year (e.g. requests made in 2018 will receive information regarding 2017 sharing activities).
Even though we do not sell or share your information with any third parties except for the licensed insurance carriers in our network, you can still submit a request to obtain this information. Please send an email message to <a href="mailto:info@dialautocoverage.com" className='text-blue-500 underline'>info@dialautocoverage.com</a> with “Request for California Privacy Information” on the subject line and in the body of your message. We will provide the requested information to you at your e-mail address in response. Please be aware that not all information sharing is covered by the “Shine the Light” requirements and only information on covered sharing will be included in our response.</p><br />
          
          <h6 className='font-bold text-lg'>Information Retention and Right to Delete</h6>
          <p>Under the California Consumer Protection Act of 2018, a consumer has the right to request, via verifiable request method, that dialautocoverage.com delete any personal information about the consumer that has been collected. Upon receipt of such request, dialautocoverage.com shall delete the information and shall direct its insurance carriers to delete the information from its records as well, except under limited circumstances where the consumer’s information is required to: (1) compute the transaction for which the personal information was collected, provide a good or service requested by the consumer, or reasonably anticipated within the context of dialautocoverage.com’s ongoing business relationship with the consumer, or otherwise perform a contract between dialautocoverage.com and the consumer; (2) detect security incidents; protect against malicious, deceptive, fraudulent, or illegal activity; or prosecute those responsible for that activity; (3) debug to identify and repair errors existing intended functionality; (4) exercise free speech, ensure the right of another consumer to exercise his/her right of free speech, or exercise another right provided for by law; (5) comply with the California Electronic Communications Privacy Act; (6) engage in public or peer-reviewed scientific, historical, or statistical research in the public interest; (7) to enable solely internal uses that are reasonably aligned with the expectations of the consumer based on the consumer’s relationship with dialautocoverage.com; (8) comply with a legal obligation; (9) otherwise use the consumer’s personal information, internally, in a lawful manner that is compatible with the context in which the consumer provided the information.
Any information you provide to dialautocoverage.com will be retained until you make the decision to cancel your account with us. If you want to cancel your account or if you want to request that we no longer use your information to provide you with products and services, you can contact us at <a href="mailto:info@dialautocoverage.com" className='text-blue-500 underline'>info@dialautocoverage.com</a>. Even after this request, your information may be retained for the appropriate amount of time to comply with various legal and statutory obligations.</p><br />

          <h6 className='font-bold text-lg'>Right to Not Be Discriminated Against</h6>
          <p>Should you decide to exercise any of the above-mentioned rights under the California Consumer Protection Act, dialautocoverage.com is prohibited from discriminating against that consumer for that exercise. However, important to note is that dialautocoverage.com also offers a different price, rate, level, or quality of goods or services to the consumer if that price or difference is directly related to the value provided to the consumer by the consumer’s data.</p>
        </div>
    </div>
  )
}

export default page